### PR TITLE
Get release path variable

### PR DESCRIPTION
**Pull request by magi2c**
To share custom tasks between the deploy and rollback.

Example hook:

ansistrano_after_cleanup_tasks_file

```
- name: doctrine:cache:clear-metadata
  shell: chdir={{ ansistrano_release_path.stdout }}
    php app/console doctrine:cache:clear-metadata --env={{dp_sf_env}} --no-debug

```

### CODE REVIEW

**Comment by ricardclau** [comment]
Why would you need that? If you roll back, your production cache will still be there right?

**Comment by ricardclau** [comment]
Now that I think about it, your production cache would be there if you use the default app/cache but not if for instance you override getCacheFolder to something like /var/cache in your AppKernel, right?

And generally speaking, even if this particular task does not need it, you may have tasks shared between deploy and rollback that may need it

I am :+1: about it, what do you think @carlosbuenosvinos @theUniC ???

**Comment by magi2c** [comment]
Yeah, In my case I have the cache in Redis. And when do rollback I have to clean the cache.

**Comment by ricardclau** [comment]
Oh, of course, I forgot about these Doctrine cache adapters, merging and retagging

Thanks @magi2c !

**Pull request merged**
